Repository Zeegomo/nwoolcan, pull requests merged in 2019-04, with the labels that each got.

#158 change milliliters with liters
  src/main/java/nwoolcan/model/brewery/production/batch/QueryBatchBuilder.java
  src/main/java/nwoolcan/model/utils/QuantityChecker.java
  src/main/java/nwoolcan/model/utils/UnitOfMeasure.java
  src/test/java/nwoolcan/model/brewery/production/batch/BatchBuilderTest.java
  src/test/java/nwoolcan/model/brewery/production/batch/BatchInfoTest.java
  src/test/java/nwoolcan/model/brewery/production/batch/BatchTest.java
  src/test/java/nwoolcan/model/brewery/production/batch/step/ModifiableStepInfoTest.java
  src/test/java/nwoolcan/model/brewery/production/batch/step/StepInfoImplTest.java
  src/test/java/nwoolcan/model/brewery/production/batch/step/StepTest.java
  src/test/java/nwoolcan/model/brewery/warehouse/WarehouseImplTest.java
  src/test/java/nwoolcan/model/brewery/warehouse/stock/StockImplTest.java
  src/test/java/nwoolcan/model/brewery/warehouse/stock/StockManagerTest.java
  src/test/java/nwoolcan/model/utils/QuantitiesTest.java
  src/test/java/nwoolcan/model/utils/QuantityTest.java
Labels: fix

#157 refactor into abstract factory for creating steps
  src/main/java/nwoolcan/model/brewery/batch/BatchBuilder.java
  src/main/java/nwoolcan/model/brewery/batch/BatchImpl.java
  src/main/java/nwoolcan/model/brewery/batch/step/BasicStep.java
  src/main/java/nwoolcan/model/brewery/batch/step/BasicStepFactory.java
  src/main/java/nwoolcan/model/brewery/batch/step/StepFactory.java
  src/main/java/nwoolcan/model/brewery/batch/step/StepHelper.java
  src/test/java/nwoolcan/model/brewery/batch/step/BasicStepFactoryTest.java
Labels: enhancement

#149 production controller first implementation (not as a class but as part of controller)
  src/main/java/nwoolcan/controller/BreweryController.java
  src/main/java/nwoolcan/controller/Controller.java
  src/main/java/nwoolcan/controller/ProductionController.java
  src/main/java/nwoolcan/model/utils/Quantities.java
  src/main/java/nwoolcan/model/utils/QuantityChecker.java
  src/main/java/nwoolcan/viewmodel/brewery/production/batch/CreateBatchDTO.java
  src/main/java/nwoolcan/viewmodel/brewery/production/batch/MasterBatchViewModel.java
  src/main/java/nwoolcan/viewmodel/brewery/production/batch/NewBatchViewModel.java
  src/main/java/nwoolcan/viewmodel/brewery/utils/QuantityViewModel.java
Labels: TODO, enhancement

#165 Database creation
  build.gradle.kts
  src/main/java/nwoolcan/model/database/Database.java
  src/main/java/nwoolcan/model/database/DatabaseJsonImpl.java
  src/main/java/nwoolcan/model/database/TypeWrapperAdapterFactory.java
  src/test/java/nwoolcan/model/database/DatabaseJsonImplTest.java
Labels: TODO

#182 fix result not safe operations and refactor
  src/main/java/nwoolcan/controller/BreweryController.java
Labels: bug, invalid

#187 Results reduce functionality
  src/main/java/nwoolcan/utils/Results.java
  src/test/java/nwoolcan/utils/ResultTest.java
Labels: enhancement

#183 add utils class for controllers
  src/main/java/nwoolcan/controller/BreweryController.java
  src/main/java/nwoolcan/controller/ControllerUtils.java
Labels: enhancement

#177 batch controller first implementation
  src/main/java/nwoolcan/controller/BreweryController.java
  src/main/java/nwoolcan/controller/Controller.java
  src/main/java/nwoolcan/controller/batch/BatchController.java
  src/main/java/nwoolcan/controller/batch/BatchControllerImpl.java
  src/main/java/nwoolcan/viewmodel/brewery/production/batch/BatchInfoViewModel.java
  src/main/java/nwoolcan/viewmodel/brewery/production/batch/DetailBatchViewModel.java
  src/main/java/nwoolcan/viewmodel/brewery/production/batch/GoNextStepDTO.java
  src/main/java/nwoolcan/viewmodel/brewery/production/batch/GoNextStepViewModel.java
  src/main/java/nwoolcan/viewmodel/brewery/production/batch/MasterStepViewModel.java
Labels: essential

#179 detail batch view first implementation
  src/main/java/nwoolcan/view/ViewType.java
  src/main/java/nwoolcan/view/production/BatchDetailController.java
  src/main/java/nwoolcan/view/production/GoNextStepModalController.java
  src/main/java/nwoolcan/view/production/ProductionController.java
  src/main/resources/nwoolcan/view/batch_detail.fxml
  src/main/resources/nwoolcan/view/go_next_step_modal.fxml
Labels: essential

#190 Logged errors when loading FXML
  src/main/java/nwoolcan/view/ViewManagerImpl.java
Labels: enhancement

#192 viewmodels and dtos for stocking a batch
  src/main/java/nwoolcan/viewmodel/brewery/production/batch/StockBatchViewModel.java
Labels: essential

#185 stock batch refactor
  src/main/java/nwoolcan/model/brewery/BreweryImpl.java
  src/main/java/nwoolcan/model/brewery/batch/Batch.java
  src/main/java/nwoolcan/model/brewery/batch/BatchImpl.java
  src/main/java/nwoolcan/model/brewery/batch/step/BasicStep.java
  src/main/java/nwoolcan/model/brewery/batch/step/StepTypeEnum.java
  src/test/java/nwoolcan/model/brewery/BreweryImplTest.java
  src/test/java/nwoolcan/model/brewery/batch/BatchTest.java
Labels: enhancement

#173 detail step view model implemetation
  src/main/java/nwoolcan/viewmodel/brewery/production/step/DetailStepViewModel.java
  src/main/java/nwoolcan/viewmodel/brewery/production/step/ParameterViewModel.java
  src/main/java/nwoolcan/viewmodel/brewery/production/step/RegisterParameterDTO.java
Labels: essential

#195 stock batch view
  src/main/java/nwoolcan/controller/batch/BatchControllerImpl.java
  src/main/java/nwoolcan/view/ViewType.java
  src/main/java/nwoolcan/view/production/BatchDetailController.java
  src/main/java/nwoolcan/view/production/GoNextStepModalController.java
  src/main/java/nwoolcan/view/production/ProductionController.java
  src/main/java/nwoolcan/view/production/StockBatchModalController.java
  src/main/java/nwoolcan/viewmodel/brewery/production/ProductionViewModel.java
  src/main/java/nwoolcan/viewmodel/brewery/production/batch/DetailBatchViewModel.java
  src/main/java/nwoolcan/viewmodel/brewery/production/batch/MasterBatchViewModel.java
  src/main/resources/nwoolcan/view/batch_detail.fxml
  src/main/resources/nwoolcan/view/production.fxml
  src/main/resources/nwoolcan/view/stock_batch_modal.fxml
Labels: essential

#206 step detail view
  src/main/java/nwoolcan/controller/ControllerUtils.java
  src/main/java/nwoolcan/controller/batch/BatchController.java
  src/main/java/nwoolcan/controller/batch/BatchControllerImpl.java
  src/main/java/nwoolcan/controller/batch/StepController.java
  src/main/java/nwoolcan/controller/batch/StepControllerImpl.java
  src/main/java/nwoolcan/view/production/BatchDetailController.java
  src/main/java/nwoolcan/view/production/StepDetailController.java
  src/main/java/nwoolcan/viewmodel/brewery/production/step/DetailStepViewModel.java
  src/main/java/nwoolcan/viewmodel/brewery/production/step/ParameterViewModel.java
  src/main/resources/nwoolcan/view/step_detail.fxml
Labels: essential

#244 production visual fixes
  src/main/java/nwoolcan/view/production/NewBatchModalController.java
  src/main/resources/nwoolcan/view/new_batch_modal.fxml
  src/main/resources/nwoolcan/view/production.fxml
Labels: enhancement, fix

#259 fix null pointer exception in step detail when registering a parameter
  src/main/java/nwoolcan/view/production/GoNextStepModalController.java
  src/main/java/nwoolcan/view/production/NewBatchModalController.java
  src/main/java/nwoolcan/view/production/StepDetailController.java
Labels: essential, fix

#257 new magic step features (so cool man)
  src/main/java/nwoolcan/controller/batch/StepControllerImpl.java
  src/main/java/nwoolcan/model/brewery/batch/BatchBuilder.java
  src/main/java/nwoolcan/model/brewery/batch/step/AbstractStep.java
  src/main/java/nwoolcan/model/brewery/batch/step/BasicStep.java
  src/main/java/nwoolcan/model/brewery/batch/step/BasicStepFactory.java
  src/main/java/nwoolcan/model/brewery/batch/step/BottlingStep.java
  src/main/java/nwoolcan/model/brewery/batch/step/DecoratorStep.java
  src/main/java/nwoolcan/model/brewery/batch/step/EnumStepFactory.java
  src/main/java/nwoolcan/model/brewery/batch/step/Step.java
  src/main/java/nwoolcan/viewmodel/brewery/production/step/DetailStepViewModel.java
  src/test/java/nwoolcan/model/brewery/batch/BatchTest.java
  src/test/java/nwoolcan/model/brewery/batch/step/EnumStepFactoryTest.java
  src/test/java/nwoolcan/model/brewery/batch/step/StepTest.java
Labels: enhancement

#248 change refence to stock in batch to the stock id
  src/main/java/nwoolcan/model/brewery/batch/Batch.java
  src/main/java/nwoolcan/model/brewery/batch/BatchImpl.java
  src/test/java/nwoolcan/model/brewery/batch/BatchTest.java
Labels: fix

#245 batch detail go next step fixes
  src/main/java/nwoolcan/view/production/GoNextStepModalController.java
  src/main/resources/nwoolcan/view/batch_detail.fxml
  src/main/resources/nwoolcan/view/go_next_step_modal.fxml
Labels: fix

#246 batch detail stock batch fixes
  src/main/java/nwoolcan/view/production/StockBatchModalController.java
  src/main/resources/nwoolcan/view/batch_detail.fxml
  src/main/resources/nwoolcan/view/stock_batch_modal.fxml
Labels: fix

#274 fix bug in BatchImpl and some minor visual in Production View
  src/main/java/nwoolcan/model/brewery/batch/BatchImpl.java
  src/main/java/nwoolcan/view/production/ProductionController.java
  src/test/java/nwoolcan/model/brewery/batch/BatchTest.java
Labels: bug, fix

#275 production add filters and changes
  src/main/java/nwoolcan/controller/BreweryController.java
  src/main/java/nwoolcan/model/brewery/BreweryImpl.java
  src/main/java/nwoolcan/model/brewery/batch/QueryBatch.java
  src/main/java/nwoolcan/model/brewery/batch/QueryBatchBuilder.java
  src/main/java/nwoolcan/view/production/ProductionController.java
  src/main/java/nwoolcan/viewmodel/brewery/production/ProductionViewModel.java
  src/main/resources/nwoolcan/view/production.fxml
Labels: enhancement, essential, fix

#283 fix alerts
  src/main/java/nwoolcan/view/AbstractViewController.java
  src/main/java/nwoolcan/view/production/BatchDetailController.java
  src/main/java/nwoolcan/view/production/StepDetailController.java
  src/main/java/nwoolcan/view/review/NewBatchEvaluationController.java
  src/main/java/nwoolcan/view/warehouse/article/ArticleDetailViewController.java
Labels: fix

#290 add to string to enums
  src/main/java/nwoolcan/model/brewery/batch/BatchMethod.java
  src/main/java/nwoolcan/model/brewery/batch/review/types/BJCPBatchEvaluationType.java
  src/main/java/nwoolcan/model/brewery/batch/step/StepTypeEnum.java
  src/main/java/nwoolcan/model/brewery/batch/step/parameter/ParameterTypeEnum.java
  src/main/java/nwoolcan/model/brewery/warehouse/article/QueryArticle.java
  src/main/java/nwoolcan/model/brewery/warehouse/stock/QueryStock.java
  src/main/java/nwoolcan/model/brewery/warehouse/stock/Record.java
Labels: enhancement, fix

#293 add parameter types for aging and fermenting step
  src/main/java/nwoolcan/model/brewery/batch/step/EnumStepFactory.java
Labels: fix

#303 Giackaloz/production/new features
  src/main/java/nwoolcan/controller/BreweryController.java
  src/main/java/nwoolcan/model/brewery/BreweryImpl.java
  src/main/java/nwoolcan/model/brewery/batch/QueryBatch.java
  src/main/java/nwoolcan/model/brewery/batch/QueryBatchBuilder.java
  src/main/java/nwoolcan/view/filters/BooleanFilter.java
  src/main/java/nwoolcan/view/production/ProductionController.java
  src/main/java/nwoolcan/viewmodel/brewery/production/ProductionViewModel.java
  src/main/java/nwoolcan/viewmodel/brewery/production/batch/MasterBatchViewModel.java
  src/main/resources/nwoolcan/view/production.fxml
Labels: essential, fix

#313 add notes in step detail
  src/main/java/nwoolcan/view/production/StepDetailController.java
  src/main/resources/nwoolcan/view/step_detail.fxml
Labels: essential

#315 fix id generator to start from 1
  src/main/java/nwoolcan/model/brewery/BatchIdGenerator.java
  src/main/java/nwoolcan/model/brewery/BreweryImpl.java
Labels: fix

#312 fix water measurements registrations
  src/main/java/nwoolcan/controller/BreweryController.java
Labels: fix

#317 move methods in interface
  src/main/java/nwoolcan/controller/file/FileController.java
  src/main/java/nwoolcan/controller/file/FileControllerImpl.java
Labels: fix

#320 Giackaloz/view/fix strings
  src/main/java/nwoolcan/model/brewery/batch/step/StepTypeEnum.java
  src/main/java/nwoolcan/view/production/BatchDetailController.java
  src/main/java/nwoolcan/view/production/GoNextStepModalController.java
  src/main/java/nwoolcan/view/production/NewBatchModalController.java
  src/main/java/nwoolcan/view/production/ProductionController.java
  src/main/java/nwoolcan/view/production/StepDetailController.java
  src/main/java/nwoolcan/view/production/StockBatchModalController.java
Labels: fix

#321 change methods name to more appropriate ones
  src/main/java/nwoolcan/controller/BreweryController.java
  src/main/java/nwoolcan/controller/file/FileController.java
  src/main/java/nwoolcan/controller/file/FileControllerImpl.java
Labels: fix

#322 fix used quantity column name`
  src/main/java/nwoolcan/view/warehouse/WarehouseViewController.java
Labels: fix

#324 move id generation at the end of constructor``
  src/main/java/nwoolcan/model/brewery/batch/BatchImpl.java
Labels: fix

#327 add 66cl bottle
  src/main/java/nwoolcan/model/brewery/batch/step/BottlingStep.java
  src/main/java/nwoolcan/model/utils/QuantityChecker.java
  src/main/java/nwoolcan/model/utils/UnitOfMeasure.java
Labels: enhancement

#330 remove ciccio ciccia
  src/main/java/nwoolcan/view/main/MainController.java
Labels: fix

#331 fix builder batch and warehouse filters
  src/main/java/nwoolcan/model/brewery/batch/BatchBuilder.java
  src/main/java/nwoolcan/model/brewery/warehouse/WarehouseImpl.java
Labels: fix

#332 fix unused fields and some other things
  src/main/java/nwoolcan/model/brewery/batch/BatchBuilder.java
  src/main/java/nwoolcan/model/brewery/batch/BatchImpl.java
  src/main/java/nwoolcan/model/brewery/batch/review/EvaluationFactory.java
  src/main/java/nwoolcan/model/brewery/batch/step/StepInfoImpl.java
  src/main/java/nwoolcan/model/database/TypeWrapperAdapterFactory.java
  src/main/java/nwoolcan/model/utils/QuantityChecker.java
  src/main/java/nwoolcan/utils/Results.java
  src/main/java/nwoolcan/view/review/BatchEvaluationDetailController.java
  src/main/java/nwoolcan/view/review/NewBatchEvaluationController.java
  src/test/java/nwoolcan/model/database/DatabaseJsonImplTest.java
Labels: fix
